name: PR Develop to Main

on:
  pull_request:
    branches:
      - develop
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup-and-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Deleta a feature branch para manter o repo limpo
      - name: Delete Feature Branch
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}
        continue-on-error: true

      # Abre o PR para a Main
      - name: Create PR to Main
        run: |
          PR_EXISTS=$(gh pr list --head develop --base main --json number -q '.[0].number')
          if [ -z "$PR_EXISTS" ]; then
            gh pr create \
              --head develop \
              --base main \
              --title "Release: Develop to Main" \
              --body "Ambiente de Develop validado. Pronto para deploy em Produção (Main)."
          else
            echo "PR para Main já existe."
          fi